recipe: default.v1
language: pt

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 2 
  - name: DIETClassifier
    epochs: 150 
    constrain_similarities: true 
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
    fallback_action_name: "action_fallback_message"

policies:
  - name: RulePolicy
  - name: MemoizationPolicy
  - name: TEDPolicy 
    epochs: 50
  - name: FormPolicy 